var fruit = ["banana", "apple", "orange", "watermelon"];
var vegetables = ["carrot", "tomato", "pepper", "lettuce"];
console.log("fruit: ", fruit);
console.log("vegetables: ", vegetables);
vegetables.pop();
console.log(vegetables);
fruit.shift();
console.log(fruit);
const num1 = fruit.indexOf("orange");
console.log(num1);
fruit.push(num1);
console.log(fruit);
const vegLength = vegetables.length;
console.log(vegLength);
vegetables.push(vegLength);
console.log(vegetables);
const food = [].concat(fruit, vegetables);
console.log(food);
food.splice(4, 2);
console.log(food);
food.reverse();
console.log(food);
food.join();
console.log(food);
